Switch to lowercase local variables and simplified error handling

diff --git a/bash/8tracks b/bash/8tracks
--- a/bash/8tracks
+++ b/bash/8tracks
@@ -6,27 +6,21 @@
 set -o pipefail
 
 err() {
-  local RED
-  RED=$(tput setaf 1)
-
-  local RESET
-  RESET=$(tput sgr0)
-
-  printf  "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $RED $* $RESET \\n"
+  printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*\\n"
   exit 1
 }
 
 api_Pull() {
-  local URL
-  URL="https://8tracks.com/users/$1/favorite_tracks?per_page=300&format=jsonh"
+  local url
+  url="https://8tracks.com/users/$1/favorite_tracks?per_page=300&format=jsonh"
 
-  local ERROR_MESSAGE
-  ERROR_MESSAGE="8tracks.com connection failed. Check connection and username"
+  local error_message
+  error_message="8tracks.com connection failed. Check connection and username"
 
   if command -v curl >/dev/null 2>&1; then
-    curl -s "${URL}" | json_Parse || err "${ERROR_MESSAGE}"
+    curl -s "${url}" | json_Parse || err "${error_message}"
   elif command -v wget >/dev/null 2>&1; then
-    wget -q -O - "${URL}" | json_Parse || err "${ERROR_MESSAGE}"
+    wget -q -O - "${url}" | json_Parse || err "${error_message}"
   else
     err "Please install curl or wget"
   fi
